-- Project Warehouse database foundation.
-- This migration is additive and intentionally does not drop or alter existing data.

CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    emp_id TEXT NOT NULL UNIQUE,
    user_name TEXT NOT NULL,
    mobile TEXT,
    email TEXT NOT NULL UNIQUE,
    user_type TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_user_type_check CHECK (user_type IN ('Administrator', 'User'))
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_code TEXT PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_permissions (
    user_id TEXT NOT NULL,
    permission_code TEXT NOT NULL,
    assigned_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, permission_code),
    CONSTRAINT user_permissions_user_fk
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT user_permissions_permission_fk
        FOREIGN KEY (permission_code) REFERENCES permissions (permission_code) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_user_permissions_permission_code
    ON user_permissions (permission_code);

CREATE TABLE IF NOT EXISTS projects (
    project_id TEXT PRIMARY KEY,
    project_name TEXT NOT NULL,
    project_status TEXT NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT projects_project_name_not_blank CHECK (length(btrim(project_name)) > 0)
);

CREATE TABLE IF NOT EXISTS project_user_mapping (
    uni_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    assigned_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT project_user_mapping_project_fk
        FOREIGN KEY (project_id) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT project_user_mapping_user_fk
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT project_user_mapping_project_user_unique UNIQUE (project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_user_mapping_user_id
    ON project_user_mapping (user_id);

CREATE TABLE IF NOT EXISTS task_master (
    task_id TEXT PRIMARY KEY,
    task_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Active',
    CONSTRAINT task_master_task_name_not_blank CHECK (length(btrim(task_name)) > 0)
);

CREATE TABLE IF NOT EXISTS tasks (
    task_id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL,
    reference_link TEXT,
    reference_document TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tasks_task_master_fk
        FOREIGN KEY (task_id) REFERENCES task_master (task_id) ON DELETE RESTRICT,
    CONSTRAINT tasks_project_fk
        FOREIGN KEY (project_id) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT tasks_description_not_blank CHECK (length(btrim(description)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks (project_id);

CREATE TABLE IF NOT EXISTS task_user_mapping (
    task_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    assigned_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, user_id),
    CONSTRAINT task_user_mapping_task_fk
        FOREIGN KEY (task_id) REFERENCES tasks (task_id) ON DELETE CASCADE,
    CONSTRAINT task_user_mapping_user_fk
        FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_task_user_mapping_user_id
    ON task_user_mapping (user_id);
