import pg from 'pg';

const { Client } = pg;

const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

const sql = `
-- 6. PROJECT USER MAPPING
CREATE TABLE IF NOT EXISTS project_user_mapping (
    uni_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    assigned_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT project_user_mapping_project_fk
        FOREIGN KEY (project_id)
        REFERENCES projects (project_id)
        ON DELETE CASCADE,

    CONSTRAINT project_user_mapping_user_fk
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT project_user_mapping_project_user_unique
        UNIQUE (project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_user_mapping_user_id
    ON project_user_mapping (user_id);

`;

async function main() {
  try {
    console.log('Connecting to PostgreSQL...');

    await client.connect();

    console.log('Connected successfully.');
    console.log('Creating Project Warehouse database schema...');

    await client.query('BEGIN');

    await client.query(sql);

    await client.query('COMMIT');

    console.log('');
    console.log('========================================');
    console.log('ALL TABLES CREATED SUCCESSFULLY');
    console.log('========================================');

  } catch (error) {
    console.error('');
    console.error('========================================');
    console.error('DATABASE SCHEMA CREATION FAILED');
    console.error('========================================');
    console.error(error);

    try {
      await client.query('ROLLBACK');
    } catch (_) {
      // Ignore rollback error
    }

    process.exitCode = 1;

  } finally {
    await client.end();
  }
}

main();