import pg from 'pg';

const { Client } = pg;

const client = new Client({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

const sql = `

CREATE TABLE IF NOT EXISTS task_user_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid BIGINT NOT NULL,
    project_id TEXT NOT NULL,
    description TEXT,
    status VARCHAR(50),
    reference_link TEXT,
    reference_document TEXT,
    assigned_to VARCHAR(100),
    assigned_on DATE,

    CONSTRAINT task_user_mapping_task_fk
        FOREIGN KEY (pid)
        REFERENCES task_master (task_id),

    CONSTRAINT task_user_mapping_project_fk
        FOREIGN KEY (project_id)
        REFERENCES projects (project_id)
        ON DELETE CASCADE
);

ALTER TABLE task_user_mapping
    ADD COLUMN IF NOT EXISTS project_id TEXT;

CREATE INDEX IF NOT EXISTS idx_task_user_mapping_pid
    ON task_user_mapping (pid);

CREATE INDEX IF NOT EXISTS idx_task_user_mapping_assigned_to
    ON task_user_mapping (assigned_to);

CREATE INDEX IF NOT EXISTS idx_task_user_mapping_project_id
    ON task_user_mapping (project_id);

`;

async function main() {
  try {
    console.log('Connecting to PostgreSQL...');

    await client.connect();

    console.log('Connected successfully.');
    console.log('Creating Project Warehouse database schema...');

    await client.query('BEGIN');

    await client.query(sql);

    await client.query('COMMIT');

    console.log('');
    console.log('========================================');
    console.log('ALL TABLES CREATED SUCCESSFULLY');
    console.log('========================================');

  } catch (error) {
    console.error('');
    console.error('========================================');
    console.error('DATABASE SCHEMA CREATION FAILED');
    console.error('========================================');
    console.error(error);

    try {
      await client.query('ROLLBACK');
    } catch (_) {
      // Ignore rollback error
    }

    process.exitCode = 1;

  } finally {
    await client.end();
  }
}

main();